### ISSUE TITLE
Funny Pack instructions are required.

### ISSUE THREAD

**Issue by rlaferla** [thiagolocatelli/Voron#3]
Please update the README to include:

- basic assembly instructions or photos/diagrams
- Need to cut two circular holes for the fans!  This is so important and until I asked on Discord, I had no idea.
- which fans to use?  Two 5015 fans
- which screws M3x?
- heatset inserts
- 8 magnets of what size?  the holes on both the housing and basket are slightly too big for press fitting 6x3 magnets
- routing of wires
- double sided tape
- Two 2 conductor Wago 221 to bridge wires
- does the basket lid need to be held on by tape?
- what goes in the basket?  activated carbon?
- additional photos/diagrams especially of how it mounts on the back of the Trident

**Comment by rlaferla** [comment]
Also Klipper config:

```
[heater_fan exhaust_fan]
##  Exhaust fan - In E2 OUT Position for Fystec Spider 1.x and 2.x
pin: PB3
max_power: 1.0
shutdown_speed: 0.0
kick_start_time: 5.0
heater: heater_bed
heater_temp: 60
fan_speed: 1.0
```

**Comment by thiagolocatelli** [comment]
Thanks for the suggestions.
