### ISSUE TITLE
Poor filtering

### ISSUE THREAD

**Issue by rlaferla** [thiagolocatelli/Voron#4]
This exhaust system does cut down some of the fumes but there's still too much that is not being filtered.  My Trident is enclosed with acrylic panels and weatherstripping.   I don't think the fans are powerful enough and I think there should be a HEPA filter added to it.

**Comment by thiagolocatelli** [comment]
I run mine at 70% during print and at 100% for 15 minutes after the print is finished. I dont notice any fume or smell from abs after. Thanks for reporting back.
