### ISSUE TITLE
Never Graver Trident measurment

### ISSUE THREAD

**Issue by spotless20** [thiagolocatelli/Voron#5]
Hey, what are the sizes for the fan holes? 

Thx

**Comment by thiagolocatelli** [comment]
@spotless20 on my sketches and the ACM panels I have ordered, they have 38.10mm diameter.

**Comment by spotless20** [comment]
okay, sry what i acully want to know what are the spacings to the top / sides of the panels, where are the holes placed, prob you should easy add your sketch
thx

**Comment by thiagolocatelli** [comment]
@spotless20 what printer/size do you have?

**Comment by spotless20** [comment]
A 200mm version, so at the best drop in for a 300 build.
